In [1]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
from sklearn.metrics import classification_report , jaccard_score,f1_score , confusion_matrix ,ConfusionMatrixDisplay ,log_loss
from sklearn.model_selection import train_test_split
from sklearn import svm 
from sklearn import preprocessing 

In [2]:
df = pd.read_csv("cell_samples.csv")
print(df.info())
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 699 entries, 0 to 698
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   ID           699 non-null    int64 
 1   Clump        699 non-null    int64 
 2   UnifSize     699 non-null    int64 
 3   UnifShape    699 non-null    int64 
 4   MargAdh      699 non-null    int64 
 5   SingEpiSize  699 non-null    int64 
 6   BareNuc      699 non-null    object
 7   BlandChrom   699 non-null    int64 
 8   NormNucl     699 non-null    int64 
 9   Mit          699 non-null    int64 
 10  Class        699 non-null    int64 
dtypes: int64(10), object(1)
memory usage: 60.2+ KB
None


ID  Clump  UnifSize  UnifShape  MargAdh  SingEpiSize BareNuc  \
0  1000025      5         1          1        1            2       1   
1  1002945      5         4          4        5            7      10   
2  1015425      3         1          1        1            2       2   
3  1016277      6         8          8        1            3       4   
4  1017023      4         1          1        3            2       1   

   BlandChrom  NormNucl  Mit  Class  
0           3         1    1      2  
1           3         2    1      2  
2           3         1    1      2  
3           3         7    1      2  
4           3         1    1      2

In [3]:
df["BareNuc"]= df["BareNuc"].notnull()
df["BareNuc"] = preprocessing.LabelEncoder().fit(df["BareNuc"]).transform(df["BareNuc"].astype(int))
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 699 entries, 0 to 698
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   ID           699 non-null    int64
 1   Clump        699 non-null    int64
 2   UnifSize     699 non-null    int64
 3   UnifShape    699 non-null    int64
 4   MargAdh      699 non-null    int64
 5   SingEpiSize  699 non-null    int64
 6   BareNuc      699 non-null    int64
 7   BlandChrom   699 non-null    int64
 8   NormNucl     699 non-null    int64
 9   Mit          699 non-null    int64
 10  Class        699 non-null    int64
dtypes: int64(11)
memory usage: 60.2 KB


In [4]:
x = df[['Clump', 'UnifSize', 'UnifShape', 'MargAdh', 'SingEpiSize',
       'BareNuc', 'BlandChrom', 'NormNucl', 'Mit']]
x_data = np.asarray(x)
x_data[:5]

array([[5, 1, 1, 1, 2, 0, 3, 1, 1],
       [5, 4, 4, 5, 7, 0, 3, 2, 1],
       [3, 1, 1, 1, 2, 0, 3, 1, 1],
       [6, 8, 8, 1, 3, 0, 3, 7, 1],
       [4, 1, 1, 3, 2, 0, 3, 1, 1]], dtype=int64)

In [5]:
x_data = preprocessing.StandardScaler().fit(x_data).transform(x_data)
x_data[:5]

array([[ 0.20693572, -0.69999505, -0.74329904, -0.63324716, -0.54956136,
         0.        , -0.17966213, -0.61182504, -0.34391178],
       [ 0.20693572,  0.28384518,  0.2668747 ,  0.76862067,  1.71010564,
         0.        , -0.17966213, -0.28411186, -0.34391178],
       [-0.50386559, -0.69999505, -0.74329904, -0.63324716, -0.54956136,
         0.        , -0.17966213, -0.61182504, -0.34391178],
       [ 0.56233637,  1.59563215,  1.61377302, -0.63324716, -0.09762796,
         0.        , -0.17966213,  1.35445405, -0.34391178],
       [-0.14846494, -0.69999505, -0.74329904,  0.06768675, -0.54956136,
         0.        , -0.17966213, -0.61182504, -0.34391178]])

In [6]:
y = df["Class"]
y_data = np.asarray(y)
y_data[:5]

array([2, 2, 2, 2, 2], dtype=int64)

In [7]:
#to truncate data into 80% to Train_data and 20% to test_data 
x_train , x_test , y_train , y_test = train_test_split(x_data,y_data,train_size=0.8 , random_state=4)
print("the training data is : ",x_train.shape ,y_train.shape )
print("the validation data i s :" , x_test.shape , y_test.shape)

the training data is :  (559, 9) (559,)
the validation data i s : (140, 9) (140,)


In [8]:
model = svm.SVC(kernel="sigmoid",gamma="auto")
model.fit(x_train,y_train)

SVC(gamma='auto', kernel='sigmoid')

In [9]:
y_pred = model.predict(x_test)
print("true data is :     " , y_test[:20])
print("predicted data is :" , y_pred[:20])

true data is :      [4 2 2 4 2 2 2 4 4 4 2 2 2 2 4 4 2 2 2 2]
predicted data is : [4 2 2 4 2 2 2 4 4 4 2 2 2 2 4 2 2 2 2 2]


In [10]:
#to convert data (2,4) into (0,1) to know accuracy such as jaccord_score and f1_score
y_test=preprocessing.LabelEncoder().fit([2,4]).transform(y_test)
y_pred=preprocessing.LabelEncoder().fit([2,4]).transform(y_pred)
print(y_test)
print(y_pred)

[1 0 0 1 0 0 0 1 1 1 0 0 0 0 1 1 0 0 0 0 0 1 0 0 0 1 0 0 1 1 0 1 0 0 0 1 0
 1 1 0 0 1 1 0 0 0 0 0 0 0 0 1 0 0 0 0 1 1 1 1 0 0 1 1 1 0 0 0 1 0 1 1 1 0
 0 0 1 0 1 0 0 0 0 0 0 0 0 1 1 0 1 0 0 1 1 1 0 1 1 0 1 0 1 0 0 0 0 0 0 0 0
 0 0 0 0 1 1 0 0 0 1 0 1 0 0 0 1 1 0 1 0 0 0 1 0 1 0 0 1 1]
[1 0 0 1 0 0 0 1 1 1 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 1 1 0 1 0 0 0 1 0
 1 1 0 0 1 1 0 0 0 0 1 0 0 0 1 0 0 0 0 1 1 1 1 0 0 1 1 1 0 1 0 1 0 0 1 1 0
 0 0 1 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 1 1 1 0 1 1 0 1 0 1 0 0 0 0 0 0 1 0
 0 0 1 0 1 1 0 0 0 1 0 1 0 0 0 1 1 0 1 0 0 0 1 0 1 0 0 1 1]


In [11]:
jaccard = jaccard_score(y_test,y_pred)
print(" the jaccard index is : ", jaccard)

 the jaccard index is :  0.8392857142857143


In [12]:
f_score = f1_score(y_test,y_pred)
print("f1 score is : ", f_score)

f1 score is :  0.9126213592233009


In [13]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.94      0.95      0.95        88
           1       0.92      0.90      0.91        52

    accuracy                           0.94       140
   macro avg       0.93      0.93      0.93       140
weighted avg       0.94      0.94      0.94       140

